server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: room
          uri: http://localhost:8081
          predicates:
            - Path=/rooms/** 
        - id: booking
          uri: http://localhost:8082
          predicates:
            - Path=/bookings/** 
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path= /mypages/**
        - id: review
          uri: http://localhost:8085
          predicates:
            - Path=/reviews/** 
        - id: alarm
          uri: http://localhost:8086
          predicates:
            - Path=/alarms/**
        - id: html
          uri: http://localhost:8087
          predicates:
            - Path=/html/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/** 
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/** 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /mypages/**
        - id: review
          uri: http://review:8080
          predicates:
            - Path=/reviews/** 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/alarms/**
        - id: html
          uri: http://html:8080
          predicates:
            - Path=/html/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
